# version: "3"

# services:
#   db:
#     image: mysql:latest
#     environment:
#       MYSQL_DATABASE: test
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 
#       MYSQL_ROOT_PASSWORD: 
#     volumes:
#       - db_data:/var/lib/mysql

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

# volumes:
#   db_data:




version: "3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"  # map host port 8080 to container port 8000

  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
